package rules

import (
	"bufio"
	"bytes"
	"compress/gzip"
	_ "embed"
	"strings"
)

// ruWordsGz is a gzipped, UTF-8, lowercased, ё→е-normalised list of Russian word
// forms, generated by cmd/dictgen. It gates auto de-hyphenation.
//
//go:embed dict/ru_words.txt.gz
var ruWordsGz []byte

var ruWords = loadRuWords()

func loadRuWords() map[string]struct{} {
	gr, err := gzip.NewReader(bytes.NewReader(ruWordsGz))
	if err != nil {
		return nil
	}
	defer gr.Close()
	m := make(map[string]struct{}, 1<<21)
	sc := bufio.NewScanner(gr)
	sc.Buffer(make([]byte, 0, 1024*1024), 1024*1024)
	for sc.Scan() {
		if w := sc.Text(); w != "" {
			m[w] = struct{}{}
		}
	}
	return m
}

// dictHas reports whether word (any case, ё or е) is a known Russian word form.
func dictHas(word string) bool {
	if len(ruWords) == 0 {
		return false
	}
	key := strings.ReplaceAll(strings.ToLower(word), "ё", "е")
	_, ok := ruWords[key]
	return ok
}
