// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ApplyCover():Promise<void>;

export function CleanTitleTags(arg1:string):Promise<string>;

export function ClearCover():Promise<void>;

export function CoverInfo():Promise<main.CoverInfoView>;

export function Export():Promise<string>;

export function GenerateCover(arg1:boolean):Promise<string>;

export function GetMetadata():Promise<main.MetaEdit>;

export function Open():Promise<main.LoadResult>;

export function Preview():Promise<string>;

export function Reload(arg1:Array<string>):Promise<main.LoadResult>;

export function SetMetadata(arg1:main.MetaEdit):Promise<void>;
