// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyCover() {
  return window['go']['main']['App']['ApplyCover']();
}

export function CleanTitleTags(arg1) {
  return window['go']['main']['App']['CleanTitleTags'](arg1);
}

export function ClearCover() {
  return window['go']['main']['App']['ClearCover']();
}

export function CoverInfo() {
  return window['go']['main']['App']['CoverInfo']();
}

export function Export() {
  return window['go']['main']['App']['Export']();
}

export function GenerateCover(arg1) {
  return window['go']['main']['App']['GenerateCover'](arg1);
}

export function GetMetadata() {
  return window['go']['main']['App']['GetMetadata']();
}

export function Open() {
  return window['go']['main']['App']['Open']();
}

export function Preview() {
  return window['go']['main']['App']['Preview']();
}

export function Reload(arg1) {
  return window['go']['main']['App']['Reload'](arg1);
}

export function SetMetadata(arg1) {
  return window['go']['main']['App']['SetMetadata'](arg1);
}
